name: Bonjour
on:
  - push
  - pull_request
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
     
      - uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
      - run: go version
      - run: make unit_test
      - run: make integration_test
      - run: make build
      - run: make package TAG=${{github.ref_name}}

      - if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v3
        with:
          username: rom2049
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: make release TAG=${{github.ref_name}}
      